// <auto-generated />

using MauiCacheDemo.Api.Shared.Enums;
using System.Text.Json.Serialization;
using MauiCacheDemo.Api.Converters;

namespace MauiCacheDemo.Api.Shared.Models
{
    public class Pet
    {
        [JsonPropertyName("id")]
        public long Id { get; set; }

        [JsonPropertyName("category")]
        public Category Category { get; set; }

        [JsonPropertyName("name")]
        public string Name { get; set; }

        [JsonPropertyName("photoUrls")]
        public List<string> PhotoUrls { get; set; }

        [JsonPropertyName("tags")]
        public List<Category> Tags { get; set; }

        [JsonConverter(typeof(PetStatusConverter))]
        [JsonPropertyName("status")]
        public PetStatus PetStatus { get; set; }
    }
}
